### ISSUE TITLE
MS07RCNA

### ISSUE THREAD

**Issue by lukasjonkers** [nickmckay/LiPDverse#10]
Hi Nick

I'm trying to open the above mentioned file (downloaded from the link in the QC [sheet](http://lipdverse.org/MS07RCNA.lpd)) in playground, but get 'Error parsing JSON-LD file. File cannot be validated'. 
I've tried opening some other files and they work fine, so I guess it's not a playground issue.

Lukas

**Comment by nickmckay** [comment]
Thanks. Looks like there's some weird characters in that file. I will fix and update on the lipdverse. You can follow along with the broader solution here, where @chrismheiser is working on solutions: https://github.com/chrismheiser/lipdnet/issues/45

**Comment by lukasjonkers** [comment]
Hi Nick,


great. Can you let me know when you've updated the file so I can update it again😉


Lukas

________________________________

**Comment by nickmckay** [comment]
Sorry, slow on this. Chris has added a feature to lipd.net to resolve this. Would you try this again? It works for me.

**Comment by lukasjonkers** [comment]
cool, I had to edit and validate, but I think it worked. Thanks.


Does this mean that the database is easier to update? If so, can I make a request for a version 0.81? Just to see and be able to work with the corrected data.


see you soon, Lukas

________________________________

**Comment by lukasjonkers** [comment]
Hi Nick,

just found the time to look into this. I opened the file I edited in JSONlint (or the other way around?) and get 46 errors (paleo0 and chron0 measurements missing). I assume this is because the google sheet from where you read the data had an empty column (but only in the measurement data). I will add the missing data (d18Oseawater) by adding a new column, but wanted to let you know the error messages I get (even though you probably get them too).

**Comment by lukasjonkers** [comment]
oops, I thought adding data was going to be easier. Do I really have to add all the metadata files manually in the playground, or is there a smarter way? Thanks

**Comment by nickmckay** [comment]
You can do it either in the playground, or on the metadata sheet. But I
have to update the files from the metadata sheet. Let me try that.

**Comment by lukasjonkers** [comment]
Thanks, I fill out the QC/metadata sheet then.

What about the errors? I checked MS11CSCN too, and get loads, whereas I think that file should be OK

**Comment by lukasjonkers** [comment]
Sorry if I'm mixing issue here

**Comment by nickmckay** [comment]
I'll check them, it shouldn't be an issue.

**Comment by lukasjonkers** [comment]
OK, thank, I'll close this one

**Comment by lukasjonkers** [comment]
I'm looking at v0.8.4 now and it seems that the LiPD file I updated hasn't made it into this version. The file I uploaded in September looks OK in playground (if a bit metadata poor, but I'd rather update that in the QC sheet)

**Comment by nickmckay** [comment]
Not exactly sure when/how this was fixed, but it looks resolved now. MS07RCNA02 is in the database and marked as a primary timeseries

**Comment by lukasjonkers** [comment]
no, it hasn't been resolved, still missing d18Oseawater. Do you want me to upload the LiPD file again?
