### ISSUE TITLE
lake sed biomarker: record not showing on map

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#11]
If a record doesn’t show up on the map attached to your email, why is that? For example, LS16THN301 is in v0.8, but is not on the map (central western Greenland). The “Primary time series” is all marked False, perhaps that’s why? Here are a couple of the lake sed biomarker records that I don’t see on the map, but are in v 0.8
LS16THN301
LS17BAHA01

**Comment by nickmckay** [comment]
It looks like this is because those records did not have year columns (only age). I've updated them, and they should be in the next version.
