### ISSUE TITLE
SS05ROTN

### ISSUE THREAD

**Issue by jessicalconroy** [nickmckay/LiPDverse#113]
There are Sr/Ca data for this record, they are not in the database:
Year     Sr/Ca       d18O
A.D.    mmol/mol    permil VPDB
1890     10.884      0.356
1891     10.598     -0.053
1892     10.544      0.639
1893     10.422      0.714
1894      10.26        0.6
1895     10.559      0.586
1896     10.707      0.583
1897     10.663      0.566
1898     10.278      0.703
1899     10.466      0.799
1900     10.537       0.77
1901     10.639      0.722
1902     10.469      0.693
1903     10.577      0.704
1904     10.424      0.339
1905     10.717      0.361
1906     10.611      0.337
1907     10.552      0.432
1908      10.66      0.496
1909     10.586      0.407
1910     10.378      0.496
1911     10.628      0.421
1912     10.488      0.591
1913     10.226      0.644
1914      10.05      0.525
1915     10.264      0.681
1916     10.464      0.536
1917     10.224      0.471
1918     10.479      0.472
1919     10.664      0.609
1920     10.497      0.485
1921     10.414       0.46
1922     10.585      0.586
1923     10.629      0.836
1924     10.372      0.767
1925     10.154      0.628
1926     10.423      0.619
1927     10.077      0.587
1928     10.377      0.266
1929     10.352      0.525
1930      10.21      0.563
1931      10.47      0.325
1932     10.562      0.478
1933     10.383      0.245
1934     10.623       0.23
1935     10.481      0.264
1936     10.526     -0.052
1937     10.531      0.247
1938     10.438      0.325
1939     10.281       0.13
1940     10.328     -0.257
1941     10.573     -0.183
1942     10.566      0.024
1943     10.408     -0.038
1944     10.396     -0.017
1945     10.403      0.276
1946     10.396      0.459
1947      10.62       0.63
1948     10.477      0.529
1949     10.505      0.428
1950     10.398      0.214
1951     10.482       0.32
1952     10.448      0.444
1953     10.201      0.461
1954     10.506      0.664
1955     10.342      0.289
1956      10.33      0.258
1957     10.344      0.255
1958     10.415      0.161
1959     10.719      0.169
1960     10.393      0.187
1961     10.132      0.295
1962     10.368      0.205
1963     10.471      0.451
1964     10.531      0.448
1965     10.143       0.22
1966     10.105      0.188
1967     10.594      0.092
1968     10.451      -0.12
1969      10.58     -0.183
1970     10.398      0.071
1971     10.165      0.191
1972     10.201      0.576
1973     10.447       0.62
1974     10.428      0.517
1975     10.264      0.465
1976     10.363      0.241
1977     10.307      0.347
1978     10.448      0.383
1979     10.489      0.531
1980     10.248      0.623
1981     10.301      0.604
1982     10.367      0.263
1983     10.196      0.375
1984     10.486      0.586
1985     10.443      0.488
1986      10.54      0.455
1987     10.495      0.382
1988     10.386      0.435
1989      10.31      0.377
1990     10.125      0.377

**Comment by nickmckay** [comment]
updated!
