### ISSUE TITLE
inferred material renaming/regrouping

### ISSUE THREAD

**Issue by aatwood1** [nickmckay/LiPDverse#116]
1. Create or merge metadata fields to a single metadata field named "inferredMaterial" (by combining isotopeInterpretation1_inferredMaterial, climateinterpretation1_inferredMaterial, paleoData_inferredMaterial)

3. Rename "paleoData_inferredMaterialGroup to "inferredMaterialGroup" (if the metadata field above is named "inferredMaterial" and not "paleoData_inferredMaterial"

**Comment by nickmckay** [comment]
ok. The official field is now "inferredMaterial" which turns into paleoData_inferredMaterial in the database. I added the 4 alternate fields to the QC sheet (climate and iso interps 1-3). We need to make sure that all of the relevant information is in the "inferedMaterial" column, then I will remove the other columns. cc: @bkonecky

**Comment by nickmckay** [comment]
Closing some old issues that should no longer be relevant
