### ISSUE TITLE
inferred vs measured/observed isotope data

### ISSUE THREAD

**Issue by aatwood1** [nickmckay/LiPDverse#117]
The coral group (and possibly others archive groups) have noted whether the isotope data was inferred or measured/observed in the metadata field: paleoData_variable type. This information needs to be merged into the paleoData_description field, which is where the other groups have appropriately put this information.

**Comment by nickmckay** [comment]
I believe that this has now been corrected in the QC sheet, and that no action is necessary on my end. Is that correct?

**Comment by aatwood1** [comment]
Yes- it looks like this issue has been resolved. The coral group moved the "inferred seawater" information into the paleoData_description field.
