### ISSUE TITLE
SL13TEAG has 4 identical records

### ISSUE THREAD

**Issue by bkonecky** [nickmckay/LiPDverse#118]
SL13TEAG has 4 records but in the lipdverse these timeseries all look identical.

Metadata has been QC'd but the data itself needs to be checked/deleted if there are duplicates. From the metadata it looks like there should be 3 real timeseries each pertaining to C26, C28, and C30 n-alkanoic acid respectively.

**Comment by nickmckay** [comment]
Oh boy. Taking a look at the data, each timeseries seems to be different, however all the data are rounded to the nearest permil, which is probably wrong, correct?

![image](https://user-images.githubusercontent.com/11466599/71836724-d74ff280-3071-11ea-84bb-c3eed8a894ee.png)

**Comment by nickmckay** [comment]
Actually, columns 1 and 5 here are identical. I've removed the duplicate (SL13TEAG01C2).

**Comment by bkonecky** [comment]
To the nearest permil is not unusual for d2H records. Does removing column 5 fix the problem?

Bronwen Konecky
Assistant Professor
Department of Earth and Planetary Sciences
Washington University
1 Brookings Drive, Campus Box 1169
St. Louis, MO, USA 63130-4899
(314) 935-3587


On January 6, 2020 at 11:48:13 AM, Nick McKay (notifications@github.com<mailto:notifications@github.com>) wrote:

Actually, columns 1 and 5 here are identical. I've removed the duplicate (SL13TEAG01C2).

**Comment by nickmckay** [comment]
Oh, we're good then. Yes, I think that fixes the problem. I'll close this out.
