### ISSUE TITLE
lake sed biomarker: how to choose "primary time series"?

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#12]
For the “Primary time series for dataset”:
 often for lipid biomarkers there are two “primary time series” at a given site: (e.g., one that tells us about terrestrial plant water isotopes, and one that tells us about aquatic plant water isotopes OR one that tells us about mean annual rainfall vs. ENSO-related rainfall). We’ll measure d2H on maybe 4 to 6 compounds, but will really only focus on two. Shall I mark two TRUE values for datasets where that’s the case? records for which this is the case:
LS14ATJU01
LS16THN301 (C24 and C28)
LS17BAHA01 (C25 and C29)
LS06SHBE01
LS14NICB01
LS13BAFL01 (C25 and C29)

**Comment by nickmckay** [comment]
Yes, I think we want every multiple timeseries marked TRUE in this case.
