### ISSUE TITLE
Unusual year data

### ISSUE THREAD

**Issue by Mattriks** [nickmckay/LiPDverse#127]
These time series have years which are seemingly either out of order or "repeated" (e.g the years run to 2000, then start again at 1950 and run again to 2000). I haven't gone back to the original data source to check why.

dataSetName|TSid|lon|lat|isoin1vG
 ---- | ---- | ---- | ---- | ---- 
 LS09MAZO|LS09MAZO|-4.68|37.48|EffectiveMoisture
MS11FAPM|MS11FAPM02|-8.9883|41.335|Temperature
MS11FAPM|MS11FAPM03|-8.9883|41.335|Temperature
MS11FAPM|MS11FAPM01|-8.9883|41.335|Temperature
MS15BATP|MS15BATP01|-9.33|38.55|Temperature

**Comment by nickmckay** [comment]
These all seem to have been resolved.
