### ISSUE TITLE
lake sed biomarker: how to choose "primary time series"? (2.0)

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#13]
sometimes authors use a mean of two (or more) biomarker d2H values for their interpretations (e.g., LS15LIDC01B, 10.1177/0959683615572852). In other cases, they show that d2H of C27 and C29 (for example) are highly correlated, and interpret both in tandem. I guess this means that both (or all) of the biomarkers they use could be considered the primary time series. Should I choose one? Or list all as true? Or none? records for which this is the case:
LS15LIDC01
LS15DOCH01
LS15DOSA01
LS15AIKA01 (C26 and C28)
LS13WASU01
LS15YAPO01

**Comment by nickmckay** [comment]
If the authors have a clear preference for one, then choose one. If they treat both equally, it's fine to put both.
