### ISSUE TITLE
Ocean2kHR_139 and CO03COPM01A

### ISSUE THREAD

**Issue by Mattriks** [nickmckay/LiPDverse#133]
In Iso2k v1.0.0, for Palmyra corals, Ocean2kHR_139 is the primary timeseries, and CO03COPM01A is a secondary timeseries (which appears the "reverse" of Ocean2kHR_139):

![Palmyra](https://user-images.githubusercontent.com/18226881/94632867-0ba9c400-030f-11eb-8367-6ad66198cf7c.png)

This mismatch seems to go back to at least https://ncdc.noaa.gov/paleo/study/1875 where the "reverse" time series can be found in the file palmyra_rawcoralsoffset.mat ("modchronf" and "modraw").

**Comment by thompsod** [comment]
The time axis is clearly reversed.  Great catch, Matt.  Not sure how this happened, but please let me know how I can help resolve Nick!

**Comment by nickmckay** [comment]
Got it. This should be fixed in the next version
