### ISSUE TITLE
Iso2k IC09OPAN wrong d18O values

### ISSUE THREAD

**Issue by chrisdane** [nickmckay/LiPDverse#139]
Hi

In the Iso2k dataset https://lipdverse.org/iso2k/1_0_0/IC09OPAN.html the `d18O (permil)` variable is the same as the `d2H (permil)` variable.

The original source has different values for d18O: https://doi.pangaea.de/10.1594/PANGAEA.871279

Cheers,
Chris

**Comment by nickmckay** [comment]
Corrected. Should be updated in next version.
