### ISSUE TITLE
lake sed biomarker: missing record from "last call" list

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#14]
There is one lake sed biomarker record that I found in the hunt during the ‘last call’, I think Darrell’s student had a LiPD file on hand, so I didn’t upload it, but doesn’t seem to be in v0.8: LS16WIGH01 (last call sheet here: https://docs.google.com/spreadsheets/d/16TSk9ceewoij8Vcs_ghHAZDwtDoqXoQ65FOckS21sNM/edit#gid=0)

**Comment by nickmckay** [comment]
Hmm.. I don't think I've received this file yet. I can check with Darrell.

**Comment by nickmckay** [comment]
Got it. Ghirla.Wirth.2016 has been added.
