### ISSUE TITLE
Iso2k IC00SC18 duplicated variables

### ISSUE THREAD

**Issue by chrisdane** [nickmckay/LiPDverse#140]
Hi

The two variables `d18O (permil) [1-1]` and `d18O (permil) [1-2]` in https://lipdverse.org/iso2k/1_0_0/IC00SC18.html are exactly the same. I dont know if this is intended.

Kind regards,
Chris

**Comment by nickmckay** [comment]
Duplicate data have been removed. Will be updated in next version of the database.
