### ISSUE TITLE
what is interpretation variable or variableGroup M

### ISSUE THREAD

**Issue by chrisdane** [nickmckay/LiPDverse#143]
Hi

What means the variable or variableGroup interpretation "M" of the precipitation record of e.g. http://lipdverse.org/globalHolocene/1_0_0/Altenweiher.DeValk.1981.html?

I could not find this information on http://wiki.linked.earth/Main_Page, http://linked.earth/ontology/ or in [McKay and Emile-Geay 2016](https://cp.copernicus.org/articles/12/1093/2016/cp-12-1093-2016-discussion.html#discussion).

Thanks!
Chris

**Comment by nickmckay** [comment]
M is a general term for "moisture-sensitive". Hydroclimate broadly speaking.

**Comment by chrisdane** [comment]
Great thanks!

**Comment by chrisdane** [comment]
And the "MODE" of https://lipdverse.org/globalHolocene/1_0_0/Tibetanus.Hammarlund.2002.html?
