### ISSUE TITLE
lake sed biomarker: records can be deleted because we don't have data

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#15]
Records that are in v0.8 but for which we don’t have proxy data so can be deleted (and added to a list of “records that meet the cut but for which we don’t have data”):
LS14NICB01
LS10NIMB01
LS09NIBB01
LS06HOBP01
LS00XIBF01
LS15YAPO01
LS95KRAL01
LS12NIGH01
LS15LIDC01

**Comment by nickmckay** [comment]
Done.
