### ISSUE TITLE
CoralHydro2k Changelog Summary not found on server

### ISSUE THREAD

**Issue by oliverbothe** [nickmckay/LiPDverse#151]
Hey Nick, 

when I try to access https://lipdverse.org/CoralHydro2k/changelogSummary.html following the link from the CoralHydro2k-page, I get the info that it is not found on the server.

**Comment by oliverbothe** [comment]
and it seems this is the case because the link should really be to https://lipdverse.org/CoralHydro2k/current_version/changelogSummary.html

**Comment by nickmckay** [comment]
Hi Oliver. Thanks, for reporting. This is a known issue that is now fixed on future updates, but hasn't been fixed retroactively. I'll see if I can change those links programmatically for all affected projects.

**Comment by nickmckay** [comment]
This should be fixed everywhere now. Thanks for reporting.
