### ISSUE TITLE
{iso2k} Year data are empty (NAs)

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPDverse#19]
In these datasets.

CO04INMI
CO17LITW01A
CO17RAPA01A
CO17WUBO1A
CO17WUBO1B
CO17WUBO1C
CO17WUBO1D
CO17WUBO1E
CO17WUBO1F
CO17WUBO1G
CO18DATO01A
CO18HECO01A
CO18HECO01B
CO18RELC01A
IC06THPR
LS01ANME
LS08STCR
LS09RUWA
LS09SHJO
LS16THN301
LS17STNU01
LS17VAWA01
LS89LATI
LS99FINE
MS11KDMS
SH18ME
SP13SUSA
SP98KUCN

**Comment by Matt-D-Jones** [comment]
Yes, LS89LATI is missing any age data - may need to remove.

**Comment by Matt-D-Jones** [comment]
Have now added age data for LS89LATI, revised lpd file e-mailed to Nick

**Comment by nickmckay** [comment]
I imported your version for LS89LATI. Other list of files now outdated.
