### ISSUE TITLE
iso2k: these datasets seem to be missing variables named "year"

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPDverse#3]
CO14ZIMG
CO17LITW01A
CO17RAPA01A
CO17WUBO1A
CO17WUBO1B
CO17WUBO1C
CO17WUBO1D
CO17WUBO1E
CO17WUBO1F
CO17WUBO1G
CO18DATO01A
CO18HECO01A
CO18HECO01B
CO18RELC01A
SH18ME
LS16THQI01
LS17BAHA01
IC06THPR
LS09SHJO
LS16THN301
LS17STNU01
LS17VAWA01
MS11KDMS
Murty.MakassarStrait.2017

**Comment by nickmckay** [comment]
Update: Murty.MakassarStrait.2017, LS09SHJO and LS16THQI01 had age columns, which have been converted to year.

**Comment by lukasjonkers** [comment]
MS11KDMS has yearTop and yearBottom. I can add a column with the mean ages.

Also, this is one of the time series that can potentially be merged with one from an earlier study. I emailed you earlier about this.

What is best, change year or merge with other time series?

**Comment by nickmckay** [comment]
updated to issue #19
