### ISSUE TITLE
remove MS11CLSB

### ISSUE THREAD

**Issue by lukasjonkers** [nickmckay/LiPDverse#36]
I discussed this very complex record (11 different biomarker isotope records on a single core) with Guillaume Leduc and because the authors even acknowledge the difficulty with interpreting the isotope data (the SBB does not appear promising as an archive for organic paleoproxy records on centennial timescales) we think it's best to delete it from the database (for now, can be included in v2 in case we learn more)

**Comment by nickmckay** [comment]
Done.
