### ISSUE TITLE
Time QC

### ISSUE THREAD

**Issue by Mattriks** [nickmckay/LiPDverse#39]
In Iso2K, time is in Years AD.  In the table below these records all have years >2018.  There appears to be some different issues here:
- "comma used as decimal point" problem resulting in large integers? (SP08VBPE, SP09REPE). 
- Ages given in Years BP? (e.g. LS00WODE, LS10HESA)
- Strange ages e.g. 2040 (SP99 DEUS), 2055.5 (LS91HOMI)?
 
dsname|lon|lat|description|time_range
----------|:-------:|:-------:|:----------:|--------------------------
IC95THHU|-77.5|-9.0|d18O of glacier ice|(0.0, 19100.0)
LS00WODE|86.57|69.23|cellulose|(50.8, 9362.2)
LS10HESA|27.67|62.25|cellulose|(128.0, 9879.0)
LS91HOMI|73.046|18.402|carbonate|(-9599.3, 2055.5)
SP06DYCN|108.08|25.28|carbonate|(-16.5, 15810.3)
SP08SPUS|-80.4|37.976|carbonate|(37.0, 6945.0)
SP08VBPE|-77.31|-5.94|carbonate|(-9.998984143e9, 9.991554642e9)
SP08VBPE|-77.31|-5.94|carbonate|(-9.873904855e9, 8.114792042e9)
SP09GRID|120.433|-8.533|carbonate|(NaN, NaN)
SP09GRID|120.433|-8.533|carbonate|(NaN, NaN)
SP09REPE|-77.183|-6.067|carbonate|(1917.0, 2.004366e6)
SP09REPE|-77.183|-6.067|carbonate|(11227.0, 1.907462e6)
SP10DOCN|110.4333|31.6667|carbonate|(10206.0, 13185.0)
SP99DEUS|-91.97|43.47|carbonate|(-5776.0, 2040.0)

**Comment by Matt-D-Jones** [comment]
LS91HOMI, years are in AD, but top dates likely result of 14C based age-depth model.

**Comment by Matt-D-Jones** [comment]
LS10HESA, LS00WODE and LS08STCR corrected to Year AD and edited lpd files e-mailed to Nick.

**Comment by nickmckay** [comment]
I was able to fix many, but not all of the SP records. LS records now look good.
