### ISSUE TITLE
Tree QC

### ISSUE THREAD

**Issue by Mattriks** [nickmckay/LiPDverse#40]
There are 4 tree d18O cellulose records that have low values.  I'm guessing that these are normalized data.  If the raw data series are already included, then the normalized records can be removed.

![treeqca](https://user-images.githubusercontent.com/18226881/50369248-492fd800-05e6-11e9-9fbe-14d7def576b3.png)

**Comment by nickmckay** [comment]
There's potentially additional value in the normalized series, as they might combine the signal from multiple sites. Will follow up with tree team
