### ISSUE TITLE
Can only delete last/righthand column from spreadsheet

### ISSUE THREAD

**Issue by lukasjonkers** [nickmckay/LiPDverse#5]
even when I select another column only the last one on the right is deleted. I realise that this is a minor issue, but I wanted to clean up some columns with only NaNs

**Comment by nickmckay** [comment]
Is this on the lipd.net/playground? (FYI @chrismheiser)

**Comment by nickmckay** [comment]
If so we'll move the issue here: https://github.com/chrismheiser/lipdnet

**Comment by lukasjonkers** [comment]
Yes, sorry for posting it on the wrong thread.

Lukas

On 27. Jul 2018, at 15:35, Nick McKay <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this on the lipd.net/playground?<http://lipd.net/playground?> (FYI @chrismheiser<https://github.com/chrismheiser>)

**Comment by nickmckay** [comment]
No worries.
