### ISSUE TITLE
{iso2k} TR data issues

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPDverse#70]
1. TR11XUPH - Missing data are displayed in graph 2 as a continuous line, while should be no data 
2. TR16LAAN - z-score data instead of raw data. We can keep this if this would be not a problem for data integration to the analysis.
3. TR12SAMU - there are 6 graphs in 1 file and they repeated 6 times. It can be count as more chronologies (replication). 

There are also some discrepancies in the site names, but this is related to metadata

WEB30c97fa8 | TR17SAMA
-- | --
WEB30c97fa82 | TR17SAMA00
WEB4632d6d9 | TR18XUGA00
WEB0738fe31 | TR18XUJA00

**Comment by Mattriks** [comment]
See #40 .  Wrt the normalised data, the raw data is needed for plots such as Latitude vs. d18O.

**Comment by nickmckay** [comment]
1. This is just a visualization issue - the way the website works. The lower graph shows that the data are indeed no data. 

2. re: #40 if someone can get me the original data, I'm happy to replace it. 

3. I think this is correct - each series is different, at least. I did rename the last one "z-score" since it's not d18O

**Comment by Matt-D-Jones** [comment]
wrt #40 TR11XUPH, TR16LAAN and TR16LAFO all still have low numbers in 0_10_o, presumable z-scores, if not removed these should not be labled as isotope data VSMOW?

**Comment by nickmckay** [comment]
This is connected to #76 closing this and moving the discussion there.
