### ISSUE TITLE
{iso2k} All year values are missing

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPDverse#84]
We have a column, but no data in the Year column for the following datasets:

CO04INMI
LS09RUWA
LS89LATI
SP13SUSA
SP89KUCN

**Comment by ekthomas** [comment]
Year (AD) data added for LS09RUWA. LiPD file attached here.
[LS09RUWA.zip](https://github.com/nickmckay/LiPDverse/files/2927172/LS09RUWA.zip)

**Comment by Matt-D-Jones** [comment]
LS89LATI file with Years complete: see e-mail of 05/02/19

**Comment by belenms** [comment]
SP13SUSA complete dataset in the attachment; note added at 'iso2k v0.10.0 QC spreadsheet' column CF 'Iso2k QC certification (INITIALS)'
[sundqvist et al, 2013, nature sci rep cold-air-cave2013isotopes.txt](https://github.com/nickmckay/LiPDverse/files/2968654/sundqvist.et.al.2013.nature.sci.rep.cold-air-cave2013isotopes.txt)

**Comment by belenms** [comment]
SP98KUCN01A  complete dataset in the attachment; note added at 'iso2k v0.10.0 QC spreadsheet' column CF 'Iso2k QC certification (INITIALS)'

[ku tl & li hc, 1998, pias s312_isotope.xlsx](https://github.com/nickmckay/LiPDverse/files/2968721/ku.tl.li.hc.1998.pias.s312_isotope.xlsx)

**Comment by thompsod** [comment]
I cannot find the age model on NCDC or Pangea, though the paper indicates that the record extends from 1957-1999.  The data on NCDC is only reported with respect to depth.  I will send an email out to the coral team to see if anyone has the chronological data for this record.

https://www.ncdc.noaa.gov/paleo-search/study/1895

[S026974910300469X.pdf](https://github.com/nickmckay/LiPDverse/files/3001455/S026974910300469X.pdf)
