### ISSUE TITLE
{iso2k} - nonstandard dataset names in Coral and Lake datasets

### ISSUE THREAD

**Issue by nickmckay** [nickmckay/LiPDverse#85]
Corals (& other hi-res marine):
Murty.MakassarStrait.2017
Carre.Saloum.2018
SH18ME

Lakes:
ClelandLake.Steinman.2016
Ghirla.Wirth.2016
ParadiseLake.Steinman.2016
SanLuisLake.Yuan.2013

**Comment by nickmckay** [comment]
We need iso2kUI type names for all of these

**Comment by Matt-D-Jones** [comment]
ClelandLake.Steinman.2016 (row 406 in QC spreadsheet)

iso2kUI added to column D - should this be in A and B as well?

All pink columns complete and QC checked.

**Comment by Matt-D-Jones** [comment]
Ghirla.Wirth.2016 (row 408 in QC spreadsheet)

iso2kUI added to column D - should this be in A and B as well?

All pink columns complete and QC checked.

Rows 409 - 413 in QC sheet are for other data so could be removed.

**Comment by Matt-D-Jones** [comment]
ParadiseLake.Steinman.2016 (row 601 in QC sheet)

iso2kUI added to column D - should this be in A and B as well?

All pink columns complete and QC checked.

Row 602 is for d13C data so could be removed.

**Comment by Matt-D-Jones** [comment]
SanLuisLake.Yuan.2013 (row 605)

iso2kUI added to column D - should this be in A and B as well?

All pink columns complete and QC checked.

Row 603 and 604 are for d13C and CaCO3 data so could be removed.

**Comment by nickmckay** [comment]
These have been updated as follows:


Corals (& other hi-res marine):
Murty.MakassarStrait.2017 to CO17MUMA
Carre.Saloum.2018updated to CO18CASA
SH18ME to SH18MEIN

Lakes:
ClelandLake.Steinman.2016 to LS16STCL
Ghirla.Wirth.2016 to LS16WIGH
ParadiseLake.Steinman.2016 to LS16STPA
SanLuisLake.Yuan.2013 to LS13YUSA

**Comment by thompsod** [comment]
Great!  Sorry for not getting to this sooner.  Glad it was resolved!
