### ISSUE TITLE
LiPD file made in playground: paleomeasurement columns misaligned

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#86]
Hey Nick and Chris,
I built a LiPD file for lake sediment record in the playground.

For some reason the data in the paleoMeasurement columns is misaligned with the headers. The data for columns 1 and 2 are the correct data for those headers, but the data for the rest of the columns in the lipd file are all jumbled up. For example, the data from column 7 is under the header for column 4 (and I can't seem to find the data for column 4). 

Any thoughts on what I'm doing wrong?

I don't know how to attach a lipd file here, so I'll send you an email with that!

Thanks,
Elizabeth

**Comment by nickmckay** [comment]
We've fixed this now I believe, but the original source of the error remains unclear, right @chrismheiser ?. Closing for now.
