### ISSUE TITLE
MS07KPPB split, again

### ISSUE THREAD

**Issue by lukasjonkers** [nickmckay/LiPDverse#87]
This did not make it into version 0.10.0 and I can't see how to re-open an issue so I do it this way

![screen shot 2019-02-20 at 10 28 09](https://user-images.githubusercontent.com/38979118/53081043-4c6a1600-34fa-11e9-9029-703d67ec46fe.png)

**Comment by lukasjonkers** [comment]
unfortunately I don't think I still have the files, let me know if you don't have them anymore (I uploaded them on Dec 13) so I can have a look in my back ups

**Comment by nickmckay** [comment]
OK, this likely got lost when I had to redo the updates. I'll look into it.

**Comment by nickmckay** [comment]
Updated into version 0.11.0 with older files. May need additional QCing.
