### ISSUE TITLE
missing Year AD in LS16THN3 lipd file: 

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/LiPDverse#89]
I have been trying to add the Year AD to the LS16THN3, because I believe this is why the data aren't displaying in the lipdverse. For some reason, the playground freezes whenever I add the Year AD column. I attach here the most recent lipd file without ages (note that this lipd file has been corrected, as the current version int he lipdverse is missing a couple of row numbers-Chris helped find & solve this problem) and an excel sheet with the ages.

[LS16THN301_YearAD.xlsx](https://github.com/nickmckay/LiPDverse/files/2928394/LS16THN301_YearAD.xlsx)
[LS16THN301.zip](https://github.com/nickmckay/LiPDverse/files/2928395/LS16THN301.zip)

**Comment by nickmckay** [comment]
I think I resolved this. I suspect the issues with the file in the playground was that there was an age ensemble in the paleoData. Something we should prevent R from writing out.

Check this file in v.11.
