### ISSUE TITLE
LS03RUED coordinates

### ISSUE THREAD

**Issue by belenms** [nickmckay/LiPDverse#90]
not sure if I've to re-open LS03RUED by Matt-D-Jones or submit a new issue;  so I copy paste here too: LS03RUED wrong coordinates? Atlantic lake? is it not Central Africa? paper: Lake Edward (0º-0º40'S, 29º20'-29º50'E, 912 m a.s.l.) is located on the border separating Uganda from the Democratic Republic of the Congo, in the western arm of the East African rift valley … change 29.5 W to 29.5 E

**Comment by nickmckay** [comment]
Fixed.
