### ISSUE TITLE
SL13TEAG and SL13TEAK  paleoData_values stored as cell rather than double

### ISSUE THREAD

**Issue by bkonecky** [nickmckay/LiPDverse#98]
SL13TEAG and SL13TEAK (2 records each) have paleoData_values stored as cell rather than double. (Matlab distribution of database)

They are also missing values in paleoData_Iso2kUI.

**Comment by nickmckay** [comment]
Fixed!

**Comment by nickmckay** [comment]
actually, only fixed the character values, iso2kUI still needs to be populated
